### ISSUE TITLE
Sequence is not working when redeploying the pods.

### ISSUE THREAD

**Issue by Nethminiromina** [ThalesGroup/helm-spray#73]
Hello, I am using Helm Spray to deploy helm sub-charts in EKS in a sequence. This works perfectly when I am deploying the pods in a new namespace or when I delete the deployed releases and redeploy the new version.

But when I try to redeploy the pods without deleting the deployed release, the sequence doesn't work (means all the pods try to start at the same time). 

The command I am using to deploy the pods:
```
helm spray repo/platform --version 1.27.0-build-10 -n dev --set 'global.replicas=1' --set 'global.profiles.extra=dynamic' --debug
```

Am I missing a step or is there another way to achieve this task?

**Comment by cvila84** [comment]
Hello,

Spray relies on liveness/readiness to move on from one weight to another. So indeed, if pods from previous release are still up and running, all upgrade commands will be run in a row.

That's an interesting catch, because it would be good to keep the same behavior of ordering the upgrades (especially if there are new API dependencies between the sub-charts).

I will check how we can improve the weight management.

**Comment by cvila84** [comment]
There is actually a bug in the weight policy that does not take into account the status.updatedReplicas field that precisely helps to determine if all pods are upgraded. I will work on a fix ASAP

**Comment by Nethminiromina** [comment]
Great @cvila84

**Comment by cvila84** [comment]
Should be fixed in 4.0.9 !

**Comment by jroucheton** [comment]
Thank you for this fix.

**Comment by Nethminiromina** [comment]
Thank you @cvila84 for the fix.
